nome = str(input('Digite seu nome completo: ')).strip().title()
print(nome.upper())
print(nome.lower())
print(len(nome) - nome.count(' '))
#print(nome.find(' '))
separador = nome.split()
print(len(separador[0]))
