n = int(input('Digite um numero: '))
print('-' * 12)
print('0 x {:2} = {}'.format(n, n*0))
print('1 X {:2} = {}'.format(n, n*1))
print('2 X {:2} = {}'.format(n, n*2))
print('3 X {:2} = {}'.format(n, n*3))
print('4 X {:2} = {}'.format(n, n*4))
print('5 X {:2} = {}'.format(n, n*5))
print('6 X {:2} = {}'.format(n, n*6))
print('7 X {:2} = {}'.format(n, n*7))
print('8 X {:2} = {}'.format(n, n*8))
print('9 X {:2} = {}'.format(n, n*9))
print('10 X {} = {}'.format(n, n*10))
print('-' * 12)
